#!/bin/bash

case "$1" in
	appdog)
		#install appdog
		if test -e /etc/init.d/appdog
		then
        		echo "appdog has been installed, skip"
		else
        		echo "installing appdog ..."
        		cp giiwa/modules/default/view/admin/clone/init.d/appdog /etc/init.d/appdog
        		cp -r giiwa/modules/default/view/admin/clone/appdog /etc/
        		cd /etc/init.d/
        		chkconfig /etc/init.d/appdog on
        		cd -
        		echo "appdog has been installed in /etc/init.d/"
		fi
		;;
	postgresql)
		#initial postgresql
		echo "initdb using dbinit.sql"
		sudo -u postgres psql < giiwa/modules/default/view/admin/clone/dbinit.sql
		echo "initdb has been done"
		;;
	mongo)
		#checking mongo
		echo "init mongo data"
		sudo mkdir -p /opt/data/db
		sudo cp giiwa/modules/default/view/admin/clone/opt/mongodb/bin/m.sh /opt/mongodb/bin
		sudo chmod ugo+x /opt/mongodb/bin/m.sh
		echo "mongo m.sh has been copy to /opt/mongodb/bin/"
		;;
	*)
		echo "Usage: install {appdog|postgresql|mongo}"
esac

