apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'

group = 'org.giiwa'
version = '3.4'
description = 'giiwa distributed web framework'

sourceCompatibility = 17
targetCompatibility = 17

def buildno = new Date().format("yyMMddHHmm")

tasks.withType(JavaCompile) {
	options.encoding = 'UTF-8' 
	options.warnings = false 
}
 
println description
println 'buildno: ' + buildno

repositories {
     maven { url "https://repo1.maven.org/maven2" }
     maven { url "https://repo.osgeo.org/repository/release/"}
     maven { url "https://maven.aliyun.com/repository/public/" }
     //maven { url "https://download.dcache.org/nexus/repository/public/"}
     maven { url "https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/" }
     maven { url "https://artifacts.alfresco.com/nexus/content/repositories/releases/" }
     
     mavenCentral()
}

configurations.all() {
    Configuration configuration ->
        configuration.resolutionStrategy.failOnVersionConflict()
}

dependencies {

	// GPLv2 with Classpath Exception， 仅限修改库本身需要开源, used by dao/X
	implementation ('org.openjdk.nashorn:nashorn-core:15.4')
	
    //Apache 2.0
    //implementation("org.codehaus.groovy:groovy-jsr223:3.0.25")

    //Apache 2.0
    //implementation("org.codehaus.groovy:groovy-all:3.0.25")

    // Source: https://mvnrepository.com/artifact/org.projectlombok/lombok
    //implementation("org.projectlombok:lombok:1.18.46")

	// Source: https://mvnrepository.com/artifact/org.apache.avro/avro
	//Apache 2.0
    implementation("org.apache.avro:avro:1.12.1"){
        exclude group: 'org.slf4j',module: 'slf4j-api'
    }

    // Source: https://mvnrepository.com/artifact/it.unimi.dsi/fastutil
    //Apache 2.0
    //implementation("it.unimi.dsi:fastutil:8.5.18")
    
	// BSD-style license, used by net/client/SSH
	implementation ('com.github.mwiede:jsch:0.2.23')
    
    //Apache 2.0, used by net/client/*
    implementation ('commons-net:commons-net:3.12.0'){
        exclude group: 'commons-io',module: 'commons-io'
    }
	
	//Apache 2.0
	// Source: https://mvnrepository.com/artifact/software.amazon.awssdk/s3
    implementation("software.amazon.awssdk:s3:2.54.2")

    //Apache 2.0
    // Source: https://mvnrepository.com/artifact/com.huaweicloud/esdk-obs-java
    implementation("com.huaweicloud:esdk-obs-java:3.26.6") {
        exclude group: 'org.jetbrains.kotlin',module: 'kotlin-stdlib'
        exclude group: 'com.squareup.okhttp3',module: 'okhttp'
        exclude group: 'com.fasterxml.jackson.core',module: 'jackson-core'
        exclude group: 'com.fasterxml.jackson.core',module: 'jackson-databind'
        exclude group: 'com.fasterxml.jackson.core',module: 'jackson-annotations'
        exclude group: 'com.squareup.okio',module: 'okio'
    }

	//Apache 2.0, used by dfile/NfsDfile
    implementation ('com.emc.ecs:nfs-client:1.1.0') {
        exclude group: 'org.apache.commons',module: 'commons-lang3'
    }

    // Source: https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk18on
    implementation("org.bouncycastle:bcprov-jdk18on:1.84")

    // Source: https://mvnrepository.com/artifact/org.bouncycastle/bcpkix-jdk18on
    implementation("org.bouncycastle:bcpkix-jdk18on:1.84")

	//LGPL 2.1, used by dfile/SmbFile
	implementation ('org.codelibs:jcifs:2.1.40') {
        exclude group: 'org.bouncycastle',module: 'bcprov-jdk18on'
	}
	
	//Apache 2.0, used by mq/RabbitMQ
	implementation("com.rabbitmq:amqp-client:5.25.0")
			
	//Apache 2.0, used by server/Server
	implementation ('org.eclipse.jetty.ee10:jetty-ee10-servlet:12.0.16'){
        exclude group: 'org.slf4j',module: 'slf4j-api'
	}
			
	//EPL 2.0, used by mq/MQTT
    implementation("org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5")
		
	//Apache 2.0, used by misc/Host
    implementation ('org.fusesource:sigar:1.6.4') {
    	exclude group: 'log4j',module: 'log4j'
    }
        
	//MIT license, used by cache/RedisCache
    implementation("redis.clients:jedis:7.5.2"){
    	//exclude group: 'org.slf4j',module: 'slf4j-api'
    	exclude group: 'org.apache.commons',module: 'commons-pool2'
    	exclude group: 'com.google.code.gson',module: 'gson'
    }
    
	//Apache 2.0
	//implementation ('io.milvus:milvus-sdk-java:2.5.5'){
	//	exclude group: 'com.google.protobuf', module: 'protobuf-java'
	//	exclude group: 'org.apache.commons', module: 'commons-text'
	//	exclude group: 'com.google.guava', module: 'guava'
	//	exclude group: 'org.apache.commons', module: 'commons-lang3'
	//	exclude group: 'com.google.errorprone', module: 'error_prone_annotations'
	//	exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
	//	exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-common'
	//	exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib'
	//}

	//Apache 2.0
	//implementation("org.neo4j.driver:neo4j-java-driver:5.28.4")

    //Apache 2.0, used by snmp/SampleAgent
	implementation ('org.snmp4j:snmp4j-agent:3.5.4')

	//Apache 2.0, used by task/SecurityTask
	implementation ('commons-io:commons-io:2.20.0')
	  
	//Apache 2.0, used by misc/MD5
	implementation ('org.apache.commons:commons-compress:1.28.0'){
        //exclude group: 'commons-io',module: 'commons-io'
    }
 
	//Apache 2.0, used by conf/YamlHelper
	implementation ('org.yaml:snakeyaml:2.2')
      
    //Apache License, Version 2.0, used by conf/Config
    implementation ('org.apache.commons:commons-configuration2:2.5'){
    	exclude group: 'org.apache.commons',module: 'commons-lang3'
    }
        
    //Apache License, Version 2.0, used by cache/RedisCache
    implementation ('org.apache.commons:commons-pool2:2.12.0')

	//BSD License, used by sql/SqlParser
	implementation ('org.antlr:antlr4:4.11.1')

	//Apache 2.0, used by mq/RabbitMQ
    //implementation ('org.apache.activemq:activemq-client:5.17.1') {
    //	exclude group: 'org.slf4j',module: 'slf4j-api'
    //}

	//Apache 2.0, used by mq/RocketMQ
    //implementation ('org.apache.rocketmq:rocketmq-client:5.0.0') {
    //	exclude group: 'commons-codec',module: 'commons-codec'
    //	exclude group: 'org.apache.commons',module: 'commons-lang3'
    //	exclude group: 'com.google.guava',module: 'guava'
    	//exclude group: 'com.alibaba',module: 'fastjson'
    //	exclude group: 'org.slf4j',module: 'slf4j-api'
	//	exclude group: 'io.netty',module: 'netty-all'
    //}

	//LGPL 2.1, used by bean/GLog
    // Source: https://mvnrepository.com/artifact/org.graylog2/syslog4j
    implementation("org.graylog2:syslog4j:0.9.63"){
    	exclude group: 'org.apache.commons',module: 'commons-lang3'
	}
    
    //Apache 2.0, used by view/VelocityView
    implementation ("org.apache.velocity:velocity-engine-core:2.3"){
    	exclude group: 'org.apache.commons',module: 'commons-lang3'
    	exclude group: 'org.slf4j',module: 'slf4j-api'
    }
        
    //Apache 2.0, used by web/RequestHelper
	implementation ('org.apache.commons:commons-fileupload2-jakarta:2.0.0-M1'){
    	exclude group: 'commons-io',module: 'commons-io'
	}
    
    //BSD style license, used by web/Module
    implementation ('dom4j:dom4j:1.6.1') {
    	exclude group: 'xml-apis',module: 'xml-apis'
    }
    
    //MIT License, used by misc/Html 
    implementation ('org.jsoup:jsoup:1.22.1')
    
    //Apache Software License, Version 2.0, used by misc/GImage
    implementation ('com.google.zxing:core:3.4.1')
    
    //Apache 2.0 license, used by json/JSON
    implementation ('com.google.code.gson:gson:2.10.1')
    
	//Apache 2 license, used by client/Http
	implementation ('org.jetbrains.kotlin:kotlin-stdlib:2.2.21')
    
	//Apache License 2.0, used by client/Http
    implementation ('com.squareup.okhttp3:okhttp:5.3.2'){
    	exclude group: 'org.jetbrains.kotlin',module: 'kotlin-stdlib'
    	//exclude group: 'org.jetbrains.kotlin',module: 'kotlin-stdlib-jdk7'
    	//exclude group: 'org.jetbrains.kotlin',module: 'kotlin-stdlib-jdk8'
    	//exclude group: 'org.jetbrains.kotlin',module: 'kotlin-stdlib-common'
    }

	//MIT license, used by conf/Config
    implementation ('org.slf4j:slf4j-log4j12:1.7.36')

    //Apache 2.0, used by dao/MongoHelper
    implementation ('org.mongodb:mongodb-driver-sync:5.7.0')
    //implementation("org.mongodb:mongodb-driver-sync:5.1.4")

    //GNU General Public License (GPL) version 2, used by driver/MySQL
    implementation ('com.mysql:mysql-connector-j:8.4.0'){
        exclude group: 'com.google.protobuf',module: 'protobuf-java'
    }

    // Source: https://mvnrepository.com/artifact/org.mariadb.jdbc/mariadb-java-client
    implementation("org.mariadb.jdbc:mariadb-java-client:3.5.9")
	
	//BSD 2-Clause "Simplified" License, used by driver/PG
	implementation ('org.postgresql:postgresql:42.7.4')
	
	//BSD 2-clause
	// Source: https://mvnrepository.com/artifact/org.opengauss/opengauss-jdbc
	//这个驱动与postgresql驱动冲突
    //implementation("org.opengauss:opengauss-jdbc:6.0.3")

	//Apache License 2.0, used by dao/SequoiadbHelper
    //implementation files('lib/sequoiadb-driver-5.10.jar')
    
    //Apache License 2.0, used by driver/DM
    //implementation files('lib/DmJdbcDriver11.jar')
    
}

task prepare(dependsOn: [build]) {
	doLast {
		try{
			exec { 
				commandLine 'git', 'add', '.'
			}
			exec {
				commandLine 'git', 'commit', '-m', 'auto commit'
			}
			exec {
				commandLine 'git', 'tag', version + '.' + buildno
			}
			exec { 
				commandLine 'git', 'push', '--tags'
			}
		}catch(Exception e){
			println e
		}

		copy{
		    from('deploy')
		    into('build/giiwa/giiwa/')
		}

		copy{
			println 'copy modules'
		    from('src/main/modules')
		    into('build/giiwa/giiwa/modules')
		}
		
		def xml1 = new BufferedReader(new FileReader(new File('src/main/modules/default/module.xml')))
		def xml2 = new PrintStream(new File('build/giiwa/giiwa/modules/default/module.xml'))
		def line = xml1.readLine()
		while( line != null ){
			if( line.indexOf('>0<')>-1 ){
				line = line.replace('<build>0</build>', '<build>' + buildno + '</build>')
			}
			xml2.println(line)
			line = xml1.readLine();
		}
		xml1.close();
		xml2.close();

		copy{
			println 'copy depends to lib'
		    from configurations.runtimeClasspath
		    into('build/giiwa/giiwa/lib')
		}
		copy {
			println 'copy build/libs to lib'
		    from('build/libs')
		    into('build/giiwa/giiwa/lib')
		}
		copy {
			println 'copy build/libs to WEB-INF/lib'
		    from('build/giiwa/giiwa/lib')
		    into('build/giiwa/giiwa/modules/default/WEB-INF/lib')
		    exclude('sigar')
		}
		copy {
			println 'copy build/giiwa/giiwa/modules/default to upgrade'
		    from('build/giiwa/giiwa/modules/default')
		    into('build/upgrade/default')
		}
		copy {
			println 'copy build/giiwa/giiwa/lib/ to upgrade'
		    from('build/giiwa/giiwa/lib/')
		    into('build/upgrade/default/WEB-INF/lib/')
		    include('*.jar') 
		}
	}
}

task zip(type: Zip,dependsOn:prepare) {
	from 'build/giiwa'
	destinationDir file('build')
	archiveName 'giiwa-' + version + '.zip'
	
	doLast {
		println 'zip success, archived build/' + archiveName
	}
}

task tgz(type: Tar, dependsOn:prepare) {
	from 'build/giiwa'
	compression 'gzip'
	destinationDir file('build')
	archiveName 'giiwa-' + version + '.tgz'

	doLast {
		println 'tgz success, archived build/' + archiveName
	}
}

task upgrade(type: Zip,dependsOn:prepare) {
	from 'build/upgrade'
	destinationDir file('build')
	archiveName 'giiwa-' + version + '.' + buildno + '.zip'

	doLast {
		println 'zip success, archived build/' + archiveName
	}
}

task release(dependsOn: [upgrade, zip, tgz]);

task archive(type: Copy,dependsOn:release) {
	from 'build'
	into '/home/nfs/giiwa/' + version + '/'
	include "*.zip"
	include "*.tgz"
}

